# Generated by Django 6.1 on 2026-10-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title_pl', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('summary_pl', models.TextField(default='')),
                ('summary_en', models.TextField(default='')),
                ('body_pl', models.TextField(default='')),
                ('body_en', models.TextField(default='')),
                ('category', models.CharField(choices=[('postpartum_recovery', 'postpartum_recovery'), ('mental_health', 'mental_health'), ('cycle', 'cycle'), ('movement', 'movement'), ('sleep', 'sleep'), ('nutrition', 'nutrition'), ('relationships', 'relationships'), ('breastfeeding', 'breastfeeding')], max_length=22)),
                ('mode', models.CharField(choices=[('postpartum', 'postpartum'), ('cycle', 'cycle'), ('both', 'both')], default='both', max_length=10)),
                ('min_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reading_minutes', models.PositiveSmallIntegerField(default=5)),
                ('cover_emoji', models.CharField(blank=True, default='', max_length=8)),
                ('cover_image', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'category'], name='content_art_mode_2b2369_idx')],
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=40)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('website', models.URLField(blank=True, default='')),
                ('description_pl', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('is_sample', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['specialty', 'city'], name='content_spe_special_127855_idx')],
            },
        ),
    ]
