# Generated by Django 5.1.15 on 2026-10-03 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_pl', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_pl', models.TextField(default='')),
                ('description_en', models.TextField(default='')),
                ('category', models.CharField(choices=[('movement', 'movement'), ('rest', 'rest'), ('nutrition', 'nutrition'), ('mind', 'mind'), ('social', 'social'), ('recovery', 'recovery'), ('selfcare', 'selfcare')], max_length=20)),
                ('mode', models.CharField(choices=[('postpartum', 'postpartum'), ('cycle', 'cycle'), ('both', 'both')], default='both', max_length=10)),
                ('min_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('delivery_types', models.JSONField(default=list)),
                ('frequency', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly')], default='daily', max_length=10)),
                ('target_count', models.PositiveSmallIntegerField(default=1)),
                ('default_reminder_time', models.TimeField(blank=True, null=True)),
                ('safety_note_pl', models.TextField(blank=True, default='')),
                ('safety_note_en', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('movement', 'movement'), ('rest', 'rest'), ('nutrition', 'nutrition'), ('mind', 'mind'), ('social', 'social'), ('recovery', 'recovery'), ('selfcare', 'selfcare')], default='selfcare', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly')], default='daily', max_length=10)),
                ('target_count', models.PositiveSmallIntegerField(default=1)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('reminder_weekdays', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.goaltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='GoalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='goals.goal')),
            ],
            options={
                'indexes': [models.Index(fields=['goal', 'date'], name='goals_goall_goal_id_2f3973_idx')],
                'constraints': [models.UniqueConstraint(fields=('goal', 'date'), name='unique_goal_log_date')],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'is_active'], name='goals_goal_user_id_f54208_idx'),
        ),
    ]
