# Generated by Django 5.1.15 on 2026-10-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goaltemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goaltemplate',
            name='updated_at',
        ),
    ]
