# Generated by Django 5.1.15 on 2026-10-03 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('meal', 'meal'), ('night', 'night'), ('chores', 'chores'), ('errands', 'errands'), ('company', 'company'), ('siblings', 'siblings'), ('other', 'other')], default='other', max_length=20)),
                ('when_date', models.DateField(blank=True, null=True)),
                ('when_label', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'open'), ('claimed', 'claimed'), ('done', 'done'), ('cancelled', 'cancelled')], default='open', max_length=10)),
                ('claimed_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='circle_care_user_id_a35abd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CircleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('share_mood', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='circle_circ_token_733dc7_idx'), models.Index(fields=['user', 'revoked_at'], name='circle_circ_user_id_6d2b9a_idx')],
            },
        ),
    ]
