# Generated by Django 5.1.15 on 2026-10-03 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='', max_length=100)),
                ('language', models.CharField(choices=[('pl', 'pl'), ('en', 'en')], default='pl', max_length=2)),
                ('mode', models.CharField(choices=[('postpartum', 'postpartum'), ('cycle', 'cycle')], default='postpartum', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('delivery_type', models.CharField(choices=[('vaginal', 'vaginal'), ('cesarean', 'cesarean'), ('undisclosed', 'undisclosed')], default='undisclosed', max_length=12)),
                ('feeding', models.CharField(choices=[('breast', 'breast'), ('mixed', 'mixed'), ('formula', 'formula'), ('na', 'na')], default='na', max_length=10)),
                ('period_returned', models.BooleanField(default=False)),
                ('avg_cycle_length', models.PositiveSmallIntegerField(default=28)),
                ('avg_period_length', models.PositiveSmallIntegerField(default=5)),
                ('tone', models.CharField(choices=[('gentle', 'gentle'), ('motivating', 'motivating')], default='gentle', max_length=12)),
                ('checkin_reminder_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/Warsaw', max_length=64)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('worsening_factors', models.JSONField(default=list)),
                ('night_mode', models.CharField(choices=[('auto', 'auto'), ('off', 'off')], default='auto', max_length=4)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
