# Generated by Django 5.1.15 on 2026-10-03 22:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_pl', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('description_pl', models.TextField(default='')),
                ('description_en', models.TextField(default='')),
                ('steps_pl', models.JSONField(default=list)),
                ('steps_en', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('breathing', 'breathing'), ('movement', 'movement'), ('social', 'social'), ('sensory', 'sensory'), ('rest', 'rest'), ('creative', 'creative'), ('mindfulness', 'mindfulness'), ('practical', 'practical')], max_length=20)),
                ('duration_min', models.PositiveSmallIntegerField(default=5)),
                ('icon', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('hours_pl', models.CharField(default='', max_length=100)),
                ('hours_en', models.CharField(default='', max_length=100)),
                ('description_pl', models.TextField(default='')),
                ('description_en', models.TextField(default='')),
                ('is_emergency', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TrustedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('preferred_channel', models.CharField(choices=[('sms', 'sms'), ('whatsapp', 'whatsapp')], default='sms', max_length=10)),
                ('default_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('intensity', models.PositiveSmallIntegerField()),
                ('trigger', models.CharField(choices=[('manual', 'manual'), ('low_mood', 'low_mood'), ('epds', 'epds'), ('checkin_risk', 'checkin_risk')], default='manual', max_length=20)),
                ('helped', models.CharField(blank=True, choices=[('yes', 'yes'), ('somewhat', 'somewhat'), ('no', 'no')], max_length=10, null=True)),
                ('mood_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.copingstrategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'started_at'], name='support_sup_user_id_aa1d4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCopingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_score', models.PositiveSmallIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('helped_score_sum', models.FloatField(default=0.0)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='support.copingstrategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coping_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'strategy'], name='support_use_user_id_b35b0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'strategy'), name='unique_user_coping_preference')],
            },
        ),
    ]
